"""
Словарь русских названий команд → английские названия (для поиска в Football-Data.org).
Также содержит прямые ID команд для быстрого поиска (без API-запроса).
"""

from __future__ import annotations

# Маппинг русских названий → английские (для поиска через API)
TEAM_NAME_MAP: dict[str, str] = {
    # ─── Сборные ───
    "испания": "Spain",
    "австрия": "Austria",
    "россия": "Russia",
    "германия": "Germany",
    "франция": "France",
    "англия": "England",
    "италия": "Italy",
    "португалия": "Portugal",
    "нидерланды": "Netherlands",
    "голландия": "Netherlands",
    "бельгия": "Belgium",
    "хорватия": "Croatia",
    "швейцария": "Switzerland",
    "дания": "Denmark",
    "швеция": "Sweden",
    "норвегия": "Norway",
    "польша": "Poland",
    "украина": "Ukraine",
    "чехия": "Czech Republic",
    "сербия": "Serbia",
    "турция": "Turkey",
    "греция": "Greece",
    "шотландия": "Scotland",
    "уэльс": "Wales",
    "ирландия": "Ireland",
    "венгрия": "Hungary",
    "румыния": "Romania",
    "словакия": "Slovakia",
    "словения": "Slovenia",
    "бразилия": "Brazil",
    "аргентина": "Argentina",
    "колумбия": "Colombia",
    "уругвай": "Uruguay",
    "мексика": "Mexico",
    "чили": "Chile",
    "эквадор": "Ecuador",
    "перу": "Peru",
    "япония": "Japan",
    "южная корея": "South Korea",
    "корея": "South Korea",
    "австралия": "Australia",
    "иран": "Iran",
    "саудовская аравия": "Saudi Arabia",
    "катар": "Qatar",
    "сша": "USA",
    "сенегал": "Senegal",
    "марокко": "Morocco",
    "тунис": "Tunisia",
    "алжир": "Algeria",
    "нигерия": "Nigeria",
    "камерун": "Cameroon",
    "египет": "Egypt",
    "гана": "Ghana",
    "кот-д\"ивуар": "Côte d\"Ivoire",
    "кот-д’ивуар": "Côte d\"Ivoire",
    # ─── Английские клубы ───
    "манчестер сити": "Manchester City",
    "манчестер юнайтед": "Manchester United",
    "мю": "Manchester United",
    "ливерпуль": "Liverpool",
    "арсенал": "Arsenal",
    "челси": "Chelsea",
    "тоттенхэм": "Tottenham Hotspur",
    "тоттенхем": "Tottenham Hotspur",
    "ньюкасл": "Newcastle United",
    "астон вилла": "Aston Villa",
    "вест хэм": "West Ham United",
    "вест хэм юнайтед": "West Ham United",
    "брайтон": "Brighton & Hove Albion",
    "вэст бромвич": "West Bromwich Albion",
    "эвертон": "Everton",
    "кристал пэлас": "Crystal Palace",
    "фулхэм": "Fulham",
    "лидс": "Leeds United",
    "лестер": "Leicester City",
    "ноттингем форест": "Nottingham Forest",
    "волверхэмптон": "Wolverhampton Wanderers",
    "вулвз": "Wolverhampton Wanderers",
    "борнмут": "AFC Bournemouth",
    "брентфорд": "Brentford",
    # ─── Испанские клубы ───
    "барселона": "FC Barcelona",
    "реал мадрид": "Real Madrid",
    "атлетико мадрид": "Atletico de Madrid",
    "атлетико": "Atletico de Madrid",
    "севилья": "Sevilla FC",
    "вильярреал": "Villarreal CF",
    "валенсия": "Valencia CF",
    "реал сосьедад": "Real Sociedad",
    "сосьедад": "Real Sociedad",
    "бетис": "Real Betis",
    "атлетик бильбао": "Athletic Club",
    "атлетик": "Athletic Club",
    "эспаньол": "RCD Espanyol",
    "сельта": "Celta de Vigo",
    # ─── Итальянские клубы ───
    "ювентус": "Juventus",
    "интер": "Inter Milan",
    "милан": "AC Milan",
    "наполи": "SSC Napoli",
    "рома": "AS Roma",
    "лацио": "SS Lazio",
    "аталанта": "Atalanta",
    "фиорентина": "ACF Fiorentina",
    "торпед": "Torino",
    "болонья": "Bologna",
    "сассуоло": "US Sassuolo",
    "удtнезе": "Udinese",
    # ─── Немецкие клубы ───
    "бавария": "FC Bayern München",
    "бавария мюнхен": "FC Bayern München",
    "боруссия дортмунд": "Borussia Dortmund",
    "дортмунд": "Borussia Dortmund",
    "байер": "Bayer Leverkusen",
    "байер леверкузен": "Bayer Leverkusen",
    "лейпциг": "RB Leipzig",
    "айнтрахт": "Eintracht Frankfurt",
    "айнтрахт франкфурт": "Eintracht Frankfurt",
    "боруссия мёнхенгладбах": "Borussia Mönchengladbach",
    "вольфсбург": "VfL Wolfsburg",
    "штатгарт": "VfB Stuttgart",
    "вердер": "Werder Bremen",
    "хойе": "TSG Hoffenheim",
    "хоффенхайм": "TSG Hoffenheim",
    "шальке": "FC Schalke 04",
    "унион берлин": "1. FC Union Berlin",
    "унион": "1. FC Union Berlin",
    # ─── Французские клубы ───
    "псж": "Paris Saint-Germain",
    "пари сен-жермен": "Paris Saint-Germain",
    "марсель": "Olympique Marseille",
    "олимпик марсель": "Olympique Marseille",
    "лион": "Olympique Lyonnais",
    "олимпик лион": "Olympique Lyonnais",
    "монако": "AS Monaco",
    "лилль": "LOSC Lille",
    "ренн": "Stade Rennais",
    "ницца": "OGC Nice",
    "ланс": "RC Lens",
    "страсбур": "RC Strasbourg",
    "брест": "Stade Brestois",
    # ─── Португальские клубы ───
    "бенфика": "Benfica",
    "порту": "FC Porto",
    "спортинг": "Sporting CP",
    "брага": "SC Braga",
    # ─── Турецкие клубы ───
    "галтасарй": "Galatasaray",
    "фенербахче": "Fenerbahçe",
    "бешикташ": "Beşiktaş",
    "трабзонspor": "Trabzonspor",
    # ─── Другие известные клубы ───
    "зенит": "Zenit St. Petersburg",
    "спартак": "Spartak Moscow",
    "цска": "CSKA Moscow",
    "локомотив": "Lokomotiv Moscow",
    "краснодар": "FC Krasnodar",
    "динамо москва": "Dynamo Moscow",
    "динамо": "Dynamo Moscow",
    "шахтёр": "Shakhtar Donetsk",
    "шахтер": "Shakhtar Donetsk",
    "динамо киев": "Dynamo Kyiv",
    "аякс": "Ajax",
    "псв": "PSV Eindhoven",
    "фейеноорд": "Feyenoord",
    "аз алкмаар": "AZ Alkmaar",
    "андерлехт": "RSC Anderlecht",
    "брюгге": "Club Brugge",
    "генк": "KRC Genk",
    "зальцбург": "RB Salzburg",
    "ред булл зальцбург": "RB Salzburg",
    "црвена звезда": "Crvena Zvezda",
    "партизан": "Partizan",
    "сельтик": "Celtic",
    "рейнджерс": "Rangers",
    "копенгаген": "FC Copenhagen",
    "олимпиакос": "Olympiacos",
    "паок": "PAOK",
    "панатинаикос": "Panathinaikos",
}


def translate_team_name(name: str) -> str:
    """
    Переводит русское название команды в английское.
    Если перевода нет — возвращает оригинальное название.
    """
    key = name.strip().lower()
    return TEAM_NAME_MAP.get(key, name)
